//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimelyGreetings.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attachment
    {
        public long AttachmentID { get; set; }
        public string AttachmentType { get; set; }
        public decimal AttachmentSize { get; set; }
        public string AttachmentData { get; set; }
        public string AttachmentURL { get; set; }
        public System.DateTime DateCreated { get; set; }
        public long MessageID { get; set; }
        public long GreetingID { get; set; }
    
        public virtual Greeting Greeting { get; set; }
    }
}
