//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimelyGreetings.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recipient
    {
        public long RecipientID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string EmailAddress { get; set; }
        public System.DateTime DateCreated { get; set; }
        public long CreatedByUserID { get; set; }
        public long GreetingID { get; set; }
    
        public virtual User User { get; set; }
        public virtual Greeting Greeting { get; set; }
    }
}
